---
title: "Intro to R"
author: "Yingrong Chen"
date: "9/26/2021"
output: html_document
---

# Intro to R, Rstudio and Rmarkdown
1. R: is the actual programming language
2. RStudio: is an interface for using R
3. RMarkdown" creates a .Rmd file that lets you write and format. using a language called “Markdown” alongside R code

Tips
1. Console: for code that you only want to run once. Quick and easy; Nothing saves.
2. Scripts: .R files of code that you write and save
3. Environment:  lists objects specific to your current R session
4. R Cheatsheets: Help > Cheatsheets.

## Packages
R does a few things natively, so you have to teach it to do other common tasks. 
- Install the package: once on any computer, install.packages()
- Load packages: every time you turn R on, placed in a script or RMarkdown
library()
p_load(): function from the pacman package, load as many packages as you want; aautomatically installs any packages missing
pacman::p_load(): “p_load() from the pacman package.”

1 tidyverse: a bunch of packages 
+ ggplot2: data visualization
+ dplyr: data transformation verbs such as filter, select, mutate, group_by, and summarize
+ tidyr, lubridate, stringr, and forcats etc.
+ key functions, several pre-cleaned data sets
2. ggridges: Expands R's plotting abilities with the geom_ridgeline() and geom_density_ridges() family of geoms
3. Loads data sets useful for exploration, plotting, and descriptive analysis
+ palmerpenguins: penguins and penguins_raw data frames
+ gapminder: the gapminder data frame on GDP and life expectancy data 1952-2007
4. nycflights13: data frames about flights departing NYC airports in 2013
5. skimr: functions for quickly exploring and descriptively summarizing data sets

## Pipe %>%
Combining multiple operations with the pipe; focusses on verbs, not nouns
1. comes from the magrittr package by Stefan Milton Bache, loaded in the tidyverse 
2. “lexical transformation”: takes a result of whatever code you wrote before it and pipes it as the first argument to the next function after i
x %>% f(y) turns into f(x, y), and x %>% f(y) %>% g(z) turns into g(f(x, y), z) and so on. You can use the pipe to rewrite multiple operations in a way that you can read left-to-right, top-to-bottom.
3. won’t work for functions that use the current environment, e.g. assign(), get(), load(). functions that use lazy evaluation, e.g. try(), suppressMessages(), and suppressWarnings().
4. when not to use the pipe: 
4.1 when pipe has too many steps, create intermediate objects
4.2 multiple inputs or outputs
4.3 complex dependency structure

## RMarkdown
1. You Ain’t a Markup Language (YAML) Header: title, author, date, output
2. setup chunk to set certain global option
3. Code Chunk: 
Command + Option + i to create a new chunk
Command + Enter to run part of a chunk
{r [CHUNK-NAME], include=FALSE}. not to print the code or any output.
{r [CHUNK-NAME], echo=FALSE}. not to print the code, but print any output.
{r [CHUNK-NAME], eval=FALSE}. to print the code, but not any output.
4. Text Formatting: 
*Text surrounded by single asterisks* will be italicized
**Text surrounded by double asterisks** will be bold
[This is how you add a hyperlink to Google](www.google.com)

## Basic R code 
1. sum(1,2,3,4,5) evaluating a function (called sum()) with arguments (1, 2, 3, 4, and 5)
2. assigning a value to objects, the assignment operator <-
3. Equalities
= is an alternative assignment operator, like <-, e.g. n = 8 in head()
== to ask if two values or objects are equal 
4. wrapping a created object in parentheses () to both create and print 
5. Division %/%, Remainder %%

## Concepts
###Datasets, Data Frames, and Tibbles
1.  data frames: rectangular data arranged in two dimensions, rows (observation) and columns (variable)
2. tibble:  a data frame that has some slightly better default behaviors
as_tibble(): convert a traditional data frame to a tibble

###Functions
takes one or more inputs, does something to those inputs, and returns an output
E.g. The ggplot() function takes the argument data =, which has the value penguins.

####Arguments and Values
#####Named Arguments: <ARGUMENT NAME> = <VALUE>
#####Unnamed Arguments and Argument Order
Some functions specify the order of the first few arguments they expect: data = and  mapping = for ggplot.When R doesn’t have a specified order of arguments, must use named arguments
1. For the first 1-3 arguments of a function
2. For common functions use over and over again 
ggplot() and geom_xx() calls, ggsave(), filter(), select(), arrange(), and  mutate(), head(),  tail(), str(), and summary()
Functions that create statistical models, once you learn about those
Default Values: Some arguments come with a default value pre-set. 


###objects 
like new datasets or color palettes
backticks (``) around variable names that are written as multiple words with spaces in between.

vector
numbers <- c(2, 3, 5, 7, 11)

Missing Values: An Introduction
NA: if any part of any operation is done on an  NA value, it will return NA with an argument  na.rm = (the rm is short for “remove”) that can be set to make them ignore NA values. 
```{r}
sum(c(2, 3, 5, 7, 11, NA), na.rm = TRUE)
```


